In [4]:
import numpy as np

Ejercicio 1: Creación y Atributos

In [4]:
#1
edades = np.array([20, 25, 30, 35, 40])
#2
print(edades.ndim)
print(edades.shape)
print(edades.dtype)
#3
edades.dtype = np.float64
print(edades.dtype)

1
(5,)
int64
float64


Ejercicio 2: Secuencias Automáticas

In [7]:
ids_clientes = np.arange(1,101)
punto_grafico = np.linspace(0,10,50)
print(ids_clientes)
print(punto_grafico)

[  1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36
  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53  54
  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71  72
  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89  90
  91  92  93  94  95  96  97  98  99 100]
[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591

Ejercicio 3: Matrices y Datos Aleatorios

In [7]:
# 1
matriz_random = np.random.rand(3, 4)
print("Matriz aleatoria:\n", matriz_random)

# 2
matriz_unos = np.ones((3, 4))
print("Matriz de unos:\n", matriz_unos)

Matriz aleatoria:
 [[0.87455486 0.31436754 0.41933639 0.79744128]
 [0.25457067 0.71786824 0.95228243 0.432306  ]
 [0.90428818 0.35925763 0.09735724 0.79497606]]
Matriz de unos:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Ejercicio 4: El Simulador de Inventario (Integración)

In [6]:
sucursales = int(input("Ingrese la cantidad de sucursales: "))
productos = int(input("Ingrese la cantidad de productos: "))
ventas = np.zeros((sucursales, productos))
print("base de datos de inventario inicializada: ")
print(ventas)

base de datos de inventario inicializada: 
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


Ejercicio 5: Redimensionando la realidad (Reshape)

In [9]:
vector = np.arange(1,13)
vector = vector.reshape(3,4)
print("Vector reshaped a matriz 3x4:\n", vector)

Vector reshaped a matriz 3x4:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Ejercicio 6: El peso de los datos (Optimización)

In [13]:
temperatura = np.array([25.5, 28.1, 22.4, 19.9, 30.2])
print(temperatura.dtype)
temp_int = temperatura.astype(np.int32)
print(temp_int)


float64
[25 28 22 19 30]


Ejercicio 7: Simulador de Dados (Números Aleatorios Enteros)

In [14]:
dados = np.random.randint(1, 7, 10)
print("Tiradas:", dados)

Tiradas: [4 3 4 6 4 2 2 4 3 6]


Ejercicio 8: Limpieza de sensores (Conversión desde texto)

In [16]:
sensor = np.array(["45.2", "48.1", "42.5", "50.0"])
print("Datos del sensor (strings):\n", sensor)
sensor_float = sensor.astype(np.float64)
print("Datos del sensor convertidos a float:\n", sensor_float)


Datos del sensor (strings):
 ['45.2' '48.1' '42.5' '50.0']
Datos del sensor convertidos a float:
 [45.2 48.1 42.5 50. ]


Ejercicio 9: La Matriz Identidad y un pequeño "spoiler"

In [17]:
identidad = np.eye(4)
print("Matriz identidad:\n", identidad)
print("Multiplicada por 5:\n", identidad * 5)


Matriz identidad:
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Multiplicada por 5:
 [[5. 0. 0. 0.]
 [0. 5. 0. 0.]
 [0. 0. 5. 0.]
 [0. 0. 0. 5.]]
