In [1]:
import numpy as np

Ejercicio 1: Slicing y Sub-matrices

In [8]:
m = np.arange(1,26)
m = m.reshape(5,5)
print("Matriz original:\n", m)
m = m[1:4, 1:4]
print("Matriz recortada a 4x4:\n", m)

Matriz original:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Matriz recortada a 4x4:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]


Ejercicio 2: Estadísticas con Ejes (Axis)

In [ ]:
ventas = np.array([
    [1500, 2000, 1800, 2200],
    [1100, 1300, 1200, 1500],
    [3000, 3100, 2900, 3500]
])
total = np.sum(ventas)
print("Venta total:", total)
promedio_semanal = np.mean(ventas, axis=0)
print("Promedio por semana:", promedio_semanal)
max_sucursal = np.max(ventas, axis=1)
print("Máximo por sucursal:", max_sucursal)

Venta total: 26000
Promedio por semana: [2166.66666667 2133.33333333 1966.66666667 2400.        ]
Máximo por sucursal: [2200 1500 3900]


Ejercicio 3: El poder de la Máscara Booleana

Ejercicio 4: Condiciones Múltiples (El Analista de RRHH)

Ejercicio 5: Modificación Condicional

Ejercicio 6: Desafío Integrador "El Profesor Robot"